version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: kamrankazimi-postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - volleytournament_default
    restart: unless-stopped

  nextjs:
    image: ghcr.io/kamran134/kamrankazimi:latest
    container_name: kamrankazimi-next
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/public/uploads
    networks:
      - volleytournament_default
    restart: unless-stopped

networks:
  volleytournament_default:
    external: true
